server:
  port: 8443
  ssl:
    key-store: src/main/resources/nik.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: nik

logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log